#############################################################################
# Makefile for building: PageCache.app/Contents/MacOS/PageCache
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  PageCache.pro
# Template: app
# Command: /Users/austin5/Qt/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile PageCache.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I../../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/austin5/Qt/5.5/clang_64/lib
QMAKE         = /Users/austin5/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PageCache1.0.0
DISTDIR = /Users/austin5/Desktop/CacheSync/.tmp/PageCache1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/austin5/Qt/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/austin5/Qt/5.5/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		hashtable.cpp \
		trie.cpp \
		sender.cpp \
		receiver.cpp moc_mainwindow.cpp \
		moc_sender.cpp \
		moc_receiver.cpp
OBJECTS       = main.o \
		mainwindow.o \
		hashtable.o \
		trie.o \
		sender.o \
		receiver.o \
		moc_mainwindow.o \
		moc_sender.o \
		moc_receiver.o
DIST          = ../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.5/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		PageCache.pro mainwindow.h \
		hashtable.h \
		trie.h \
		sender.h \
		receiver.h main.cpp \
		mainwindow.cpp \
		hashtable.cpp \
		trie.cpp \
		sender.cpp \
		receiver.cpp
QMAKE_TARGET  = PageCache
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = PageCache.app/Contents/MacOS/PageCache

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d PageCache.app/Contents/MacOS/ || mkdir -p PageCache.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PageCache.pro ../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.5/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.5/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		PageCache.pro \
		/Users/austin5/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/austin5/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/austin5/Qt/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/austin5/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile PageCache.pro
../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.5/clang_64/mkspecs/features/qml_debug.prf:
../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.5/clang_64/mkspecs/features/uic.prf:
../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.5/clang_64/mkspecs/features/lex.prf:
PageCache.pro:
/Users/austin5/Qt/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/austin5/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/austin5/Qt/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/austin5/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile PageCache.pro

qmake_all: FORCE

PageCache.app/Contents/PkgInfo: 
	@test -d PageCache.app/Contents || mkdir -p PageCache.app/Contents
	@$(DEL_FILE) PageCache.app/Contents/PkgInfo
	@echo "APPL????" > PageCache.app/Contents/PkgInfo
PageCache.app/Contents/Resources/empty.lproj: 
	@test -d PageCache.app/Contents/Resources || mkdir -p PageCache.app/Contents/Resources
	@touch PageCache.app/Contents/Resources/empty.lproj
	
PageCache.app/Contents/Info.plist: 
	@test -d PageCache.app/Contents || mkdir -p PageCache.app/Contents
	@$(DEL_FILE) PageCache.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,none.PageCache,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,PageCache,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >PageCache.app/Contents/Info.plist

all: Makefile \
		PageCache.app/Contents/PkgInfo \
		PageCache.app/Contents/Resources/empty.lproj \
		PageCache.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h hashtable.h trie.h sender.h receiver.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp hashtable.cpp trie.cpp sender.cpp receiver.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r PageCache.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_sender.cpp moc_receiver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_sender.cpp moc_receiver.cpp
moc_mainwindow.cpp: ../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		hashtable.h \
		trie.h \
		sender.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		receiver.h \
		mainwindow.h
	/Users/austin5/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/austin5/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/austin5/Desktop/CacheSync -I/Users/austin5/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/austin5/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/austin5/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/austin5/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/austin5/Qt/5.5/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_sender.cpp: ../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		sender.h
	/Users/austin5/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/austin5/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/austin5/Desktop/CacheSync -I/Users/austin5/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/austin5/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/austin5/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/austin5/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/austin5/Qt/5.5/clang_64/lib sender.h -o moc_sender.cpp

moc_receiver.cpp: ../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		receiver.h
	/Users/austin5/Qt/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/austin5/Qt/5.5/clang_64/mkspecs/macx-clang -I/Users/austin5/Desktop/CacheSync -I/Users/austin5/Qt/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/austin5/Qt/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/austin5/Qt/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/austin5/Qt/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/austin5/Qt/5.5/clang_64/lib receiver.h -o moc_receiver.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/austin5/Qt/5.5/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		hashtable.h \
		trie.h \
		sender.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		receiver.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QBoxLayout \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpalette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		hashtable.h \
		trie.h \
		sender.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		receiver.h \
		ui_mainwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QBoxLayout \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../Qt/5.5/clang_64/lib/QtGui.framework/Headers/qpalette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

hashtable.o: hashtable.cpp hashtable.h \
		trie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hashtable.o hashtable.cpp

trie.o: trie.cpp trie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trie.o trie.cpp

sender.o: sender.cpp ../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/QtNetwork \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qabstractnetworkcache.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkcookie.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkcookiejar.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkdiskcache.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkconfigmanager.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkconfiguration.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworksession.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qauthenticator.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qdnslookup.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhostinfo.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkproxy.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qlocalserver.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qlocalsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qtcpserver.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qudpsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qssl.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslcertificate.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslcertificateextension.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslcipher.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslconfiguration.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslellipticcurve.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslerror.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslkey.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslpresharedkeyauthenticator.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qtnetworkversion.h \
		sender.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/QHostAddress
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sender.o sender.cpp

receiver.o: receiver.cpp ../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/QtNetwork \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qabstractnetworkcache.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkcookie.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkcookiejar.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkdiskcache.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkconfigmanager.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkconfiguration.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworksession.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qauthenticator.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qdnslookup.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhostaddress.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qhostinfo.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkproxy.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qlocalserver.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qlocalsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qtcpserver.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qudpsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qssl.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslcertificate.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslcertificateextension.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslcipher.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslconfiguration.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslellipticcurve.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslerror.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslkey.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslpresharedkeyauthenticator.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslsocket.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/qtnetworkversion.h \
		receiver.h \
		../../Qt/5.5/clang_64/lib/QtNetwork.framework/Headers/QHostAddress \
		../../Qt/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o receiver.o receiver.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_sender.o: moc_sender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sender.o moc_sender.cpp

moc_receiver.o: moc_receiver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_receiver.o moc_receiver.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

